# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-23 22:02
from __future__ import unicode_literals

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_issues',
            name='member_id',
        ),
        migrations.DeleteModel(
            name='Active_Issues',
        ),
        migrations.DeleteModel(
            name='Memberships',
        ),
		migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('aadhar', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('fine', models.IntegerField()),
                ('if_having_book', models.CharField(max_length=200)),
                ('if_having_movie', models.CharField(max_length=200)),
                ('if_issue_date', models.DateField(blank=True, null=True)),
                ('if_return_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
