# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20181122_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='serial',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
