# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-24 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20181124_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Issues',
            fields=[
                ('serial', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('member_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
