# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20181122_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='serial',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
