# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-24 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20181124_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active_Issues',
        ),
    ]
