# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-24 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
